//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERIES
    {
        public long DELIVERID { get; set; }
        public Nullable<long> IDOFDELIVER { get; set; }
        public Nullable<long> IDOFCUSTUMER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> RESPOND { get; set; }
        public string SOURSEADRESS { get; set; }
        public string DESTINATIONADRESS { get; set; }
        public Nullable<bool> DONE { get; set; }
        public Nullable<System.TimeSpan> HOUR { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual USERS USERS1 { get; set; }
        public virtual RATING RATING { get; set; }
    }
}
