//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTCONFIRM
    {
        public long DeliveryId { get; set; }
        public long PossibleDriveId { get; set; }
        public long NotConfirmID { get; set; }
    
        public virtual DELIVERIES DELIVERIES { get; set; }
        public virtual POSSIBLEDRIVE POSSIBLEDRIVE { get; set; }
    }
}
